# Generated by Django 4.2.5 on 2024-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_kanji',
            field=models.TextField(null=True),
        ),
    ]
